# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditWindow(object):
    def setupUi(self, EditWindow):
        EditWindow.setObjectName("EditWindow")
        EditWindow.resize(311, 273)
        self.centralwidget = QtWidgets.QWidget(EditWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 271, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.editFormLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.editFormLayout.setContentsMargins(0, 0, 0, 0)
        self.editFormLayout.setObjectName("editFormLayout")
        self.fileName_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.fileName_label.setObjectName("fileName_label")
        self.editFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fileName_label)
        self.fileName_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fileName_lineEdit.setObjectName("fileName_lineEdit")
        self.editFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fileName_lineEdit)
        self.extension_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.extension_label.setObjectName("extension_label")
        self.editFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.extension_label)
        self.extension_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.extension_lineEdit.setObjectName("extension_lineEdit")
        self.editFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.extension_lineEdit)
        self.prompt_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.prompt_label.setObjectName("prompt_label")
        self.editFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.prompt_label)
        self.prompt_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.prompt_lineEdit.setObjectName("prompt_lineEdit")
        self.editFormLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.prompt_lineEdit)
        self.fileNumber_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.fileNumber_label.setObjectName("fileNumber_label")
        self.editFormLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.fileNumber_label)
        self.fileNumber_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fileNumber_lineEdit.setObjectName("fileNumber_lineEdit")
        self.editFormLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fileNumber_lineEdit)
        self.priority_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.priority_label.setObjectName("priority_label")
        self.editFormLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.priority_label)
        self.priority_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.priority_lineEdit.setObjectName("priority_lineEdit")
        self.editFormLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.priority_lineEdit)
        self.priorityValue_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.priorityValue_label.setObjectName("priorityValue_label")
        self.editFormLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.priorityValue_label)
        self.priorityValue_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.priorityValue_lineEdit.setObjectName("priorityValue_lineEdit")
        self.editFormLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.priorityValue_lineEdit)
        self.okay_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.okay_pushButton.setGeometry(QtCore.QRect(90, 200, 131, 26))
        self.okay_pushButton.setObjectName("okay_pushButton")
        EditWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EditWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 311, 21))
        self.menubar.setObjectName("menubar")
        EditWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EditWindow)
        self.statusbar.setObjectName("statusbar")
        EditWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EditWindow)
        QtCore.QMetaObject.connectSlotsByName(EditWindow)

    def retranslateUi(self, EditWindow):
        _translate = QtCore.QCoreApplication.translate
        EditWindow.setWindowTitle(_translate("EditWindow", "MainWindow"))
        self.fileName_label.setText(_translate("EditWindow", "File name:"))
        self.extension_label.setText(_translate("EditWindow", "Extension:"))
        self.prompt_label.setText(_translate("EditWindow", "Prompt:"))
        self.fileNumber_label.setText(_translate("EditWindow", "File number:"))
        self.priority_label.setText(_translate("EditWindow", "Priority:"))
        self.priorityValue_label.setText(_translate("EditWindow", "Priority Value:"))
        self.okay_pushButton.setText(_translate("EditWindow", "Okay"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditWindow = QtWidgets.QMainWindow()
    ui = Ui_EditWindow()
    ui.setupUi(EditWindow)
    EditWindow.show()
    sys.exit(app.exec_())
