# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(351, 243)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.run_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.run_pushButton.setGeometry(QtCore.QRect(120, 130, 111, 26))
        self.run_pushButton.setObjectName("run_pushButton")
        self.settings_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.settings_pushButton.setGeometry(QtCore.QRect(120, 160, 111, 26))
        self.settings_pushButton.setObjectName("settings_pushButton")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 311, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.question1_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.question1_label.setObjectName("question1_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.question1_label)
        self.filePath_pushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.filePath_pushButton.setObjectName("filePath_pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.filePath_pushButton)
        self.filePath_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.filePath_label.setText("")
        self.filePath_label.setObjectName("filePath_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.filePath_label)
        self.question2_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.question2_label.setObjectName("question2_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.question2_label)
        self.folderPath_pushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.folderPath_pushButton.setObjectName("folderPath_pushButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.folderPath_pushButton)
        self.folderPath_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.folderPath_label.setText("")
        self.folderPath_label.setObjectName("folderPath_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.folderPath_label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 351, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.run_pushButton.setText(_translate("MainWindow", "Run"))
        self.settings_pushButton.setText(_translate("MainWindow", "Settings"))
        self.question1_label.setText(_translate("MainWindow", "File Path :"))
        self.filePath_pushButton.setText(_translate("MainWindow", "Open File"))
        self.question2_label.setText(_translate("MainWindow", "Folder Path :"))
        self.folderPath_pushButton.setText(_translate("MainWindow", "Open Folder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
